language: node_js
node_js:
  - '6.11.3'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  - CXX=g++-4.8
cache:
  directories:
    - node_modules
notifications:
  email: false
  slack:
    on_success: never
    on_failure: never
    on_pull_requests: false
before_script:
  - 'npm prune'
install:
  - 'npm install'
after_success:
  - 'npm run semantic-release'
