language: node_js
node_js:
  - 6.11.3
  - 10
cache:
  directories:
    - node_modules
notifications:
  email: false
  slack:
    on_success: never
    on_failure: never
    on_pull_requests: false
before_script:
  - npm prune
after_success:
  - npm run coveralls
  - npm run semantic-release
